name: Build and Test

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t keroliskhalaf1/react-microservices-test -f Dockerfile.dev .
      - run: docker run -e CI=true keroliskhalaf1/react-microservices-test npm run test

      - run: docker build -t keroliskhalaf1/server-microservices ./server
      - run: docker build -t keroliskhalaf1/worker-microservices ./worker
      - run: docker build -t keroliskhalaf1/client-microservices ./client
      - run: docker build -t keroliskhalaf1/nginx-microservices ./nginx

      - run: docker push keroliskhalaf1/server-microservices
      - run: docker push keroliskhalaf1/worker-microservices
      - run: docker push keroliskhalaf1/client-microservices
      - run: docker push keroliskhalaf1/nginx-microservices

      
